CREATE TABLE CAR(
   CNUM INT PRIMARY KEY AUTO_INCREMENT,
   CTITLE VARCHAR(300) NOT NULL,
   CSUBTITLE VARCHAR(300) NOT NULL, 
   CYEAR INT NOT NULL,
   CFUEL VARCHAR(20) NOT NULL,
   CKM INT NOT NULL,
   CPRICE INT NOT NULL,
   CCITY VARCHAR(20) NOT NULL,
   CIMG VARCHAR(500) NOT NULL
   
);

--   CIMG
SELECT * FROM CAR;
SELECT * FROM CFUEL WHERE TABLE_NAME='CAR';
DROP TABLE CAR;
DROP TABLE CBOARD;
DROP TABLE CMEMBER;
DROP TABLE CREPLY;
